import {collection} from './collection';
import {useState} from 'react';
export type Passage={id:string;designation:string;locator:string;monument:string;source_title:string;source_url:string;reviewed_image_links:number;site?:string;country?:string};
export function CatalogExplorer({passages,onOpen}:{passages:Passage[];onOpen:(p:Passage)=>void}){
 const [query,setQuery]=useState(''),[scope,setScope]=useState('all'),[facet,setFacet]=useState('location'),[location,setLocation]=useState(''),[period,setPeriod]=useState(''),[kind,setKind]=useState(''),[preview,setPreview]=useState<string|null>(null);
 const sites=Array.from(new Set(passages.map(p=>p.site).filter(Boolean))) as string[];
 const filtered=passages.filter(p=>{const text=scope==='passage'?p.id+' '+p.designation+' '+p.locator:scope==='monument'?p.monument:[p.id,p.designation,p.monument,p.locator,p.site,p.country].join(' ');return text.toLowerCase().includes(query.toLowerCase())&&(!location||p.site===location)&&(!period||period==='unknown')&&(!kind||kind==='reference');});
 return <><div className="query-bar"><label htmlFor="catalog-search">Search passage references</label><div className="query-input"><span aria-hidden="true">⌕</span><input id="catalog-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Passage, monument or catalog reference…"/><kbd>/</kbd></div><div className="filter-row" role="group" aria-label="Search field">{[['all','All fields'],['passage','Passage'],['monument','Monument']].map(([value,label])=><button key={value} aria-pressed={scope===value} onClick={()=>setScope(value)}>{label}</button>)}</div></div>
 <div className="facet-bar"><div className="filter-row" role="group" aria-label="Filter category">{[['location','⌖ Location'],['period','◷ Historical period'],['type','▤ Text type']].map(([value,label])=><button key={value} aria-pressed={facet===value} onClick={()=>setFacet(value)}>{label}</button>)}</div>
 {facet==='location'&&<label className="inline-filter">Location<select value={location} onChange={e=>setLocation(e.target.value)}><option value="">All locations</option>{sites.map(site=><option key={site}>{site}</option>)}</select></label>}
 {facet==='period'&&<label className="inline-filter">Period<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="">All periods</option><option value="unknown">Not catalogued</option><option disabled>Old Kingdom — metadata pending</option><option disabled>Middle Kingdom — metadata pending</option></select></label>}
 {facet==='type'&&<label className="inline-filter">Text type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">All types</option><option value="reference">Passage reference</option></select></label>}
 {(query||scope!=='all'||location||period||kind)&&<button onClick={()=>{setQuery('');setScope('all');setLocation('');setPeriod('');setKind('');}}>Clear filters</button>}</div>
 <div className="results-heading"><p role="status" aria-live="polite">{filtered.length} passage{filtered.length===1?'':'s'}</p><small>Source-reported · unreviewed</small></div>
 <div className="passage-cards">{filtered.map(p=><article className="passage-card" key={p.id}><div className="card-media">{collection.some(r=>p.id.startsWith(r.id+'-'))?<a href={'#artifact-'+collection.find(r=>p.id.startsWith(r.id+'-'))!.id}><img style={{width:'100%',height:185,objectFit:'contain'}} src={collection.find(r=>p.id.startsWith(r.id+'-'))!.image} alt={p.monument}/></a>:<button className="preview-trigger passage-art" aria-label={'Preview illustration for '+p.designation} aria-expanded={preview===p.id} onClick={()=>setPreview(preview===p.id?null:p.id)}><svg viewBox="0 0 240 130" aria-hidden="true"><path d="M15 110L90 20l60 90zM90 20l12 90M125 110l47-67 48 67M12 115h215"/></svg><span>Illustration · expand ⤢</span></button>}{p.site&&<a className="map-badge" href={'https://www.openstreetmap.org/search?query='+encodeURIComponent([p.monument,p.site,p.country].filter(Boolean).join(', '))} target="_blank" rel="noreferrer" aria-label={'Search map for '+p.monument+' (opens new tab)'}>⌖ View location ↗</a>}</div>
 {preview===p.id&&<div className="preview-note"><strong>Decorative line drawing</strong><p>This is not a facsimile. No verified photograph is linked to this passage.</p><button onClick={()=>setPreview(null)}>Close preview</button></div>}
 <div className="card-body"><small>{[p.site,p.country].filter(Boolean).join(' · ')||'Location not catalogued'}</small><h3><button id={'passage-'+p.id} onClick={()=>onOpen(p)}>{p.designation}</button></h3><p className="monument-name">{p.monument}</p><dl className="card-metadata"><div><dt>Period / dynasty</dt><dd>Not catalogued</dd></div><div><dt>Date</dt><dd>Not catalogued</dd></div><div className="wide"><dt>Catalog ID</dt><dd>{p.id}</dd></div></dl><details><summary>Passage reference & source</summary><p>{p.locator}</p><p>Edition concordance and image alignment are unreviewed.</p><a href={/^https?:\/\//.test(p.source_url)?p.source_url:undefined} target="_blank" rel="noreferrer">{p.source_title} ↗</a></details></div>
 <details className="resource-disclosure"><summary>Text resources</summary><div className="card-actions" aria-label="Text resources"><button disabled title="No sourced recitation is available">♫ Audio unavailable</button><button disabled title="No reviewed transliteration is available">Aa Transliteration unavailable</button><button disabled title="No hieroglyphic transcription is available">▤ Glyphs unavailable</button></div></details></article>)}</div>
 {!filtered.length&&<div className="empty-results"><h3>No passages match</h3><p>Try another query or clear the filters.</p></div>}
 </>;
}
