import {collection} from './collection';
import {SourceContext} from './ReaderTools';
import {CuratedCollection} from './CuratedCollection';
import {CatalogExplorer,type Passage} from './CatalogExplorer';
import {useEffect, useState, type FormEvent} from 'react';
import {AccountPanel,type Account} from './Account';
import {ReportForm,ReportQueue} from './Reports';
import {RemovalQueue} from './Removals';


type Draft = {author:string; translation_language:string; translation:string; source:string; reuse_terms:string; rights_basis:'original_work'|'permission_supported'; rights_evidence:string; notes:string; ai_assisted:boolean;terms_version:string;terms_accepted:boolean};
type Saved = Draft & {id:string; revision:number; created_on:string; review_status:string; moderation_status:string;history_may_be_truncated:boolean;can_edit:boolean;withdrawn:boolean;can_moderate:boolean;accepted_on:string|null;moderation_events:{id:number;action:string;reason:string;created_on:string;moderator:string}[]};
const blank:Draft = {author:'',translation_language:'',translation:'',source:'',reuse_terms:'CC BY-SA 4.0',rights_basis:'original_work',rights_evidence:'',notes:'',ai_assisted:false,terms_version:'2026-09-16.1',terms_accepted:false};
async function request<T>(url:string, options?:RequestInit):Promise<T>{
 const response=await fetch(url,options);
 if(!response.ok){const data=await response.json();throw new Error(typeof data.detail==='string'?data.detail:'Check the required fields and length limits.');}
 return response.json() as Promise<T>;
}
function sourceLink(url:string){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?u.href:undefined;}catch{return undefined;}}

export function Contributions(){
 const [user,setUser]=useState<Account|null>(null),[ready,setReady]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;request<Account|null>('/api/auth/me').then(u=>{if(active)setUser(u);}).catch(()=>{if(active)setError('Account status could not load. Reload to try again.');}).finally(()=>{if(active)setReady(true);});return()=>{active=false;};},[]);
 useEffect(()=>{window.dispatchEvent(new CustomEvent('ancientlens:auth-state',{detail:Boolean(user)}));},[user]);
 if(!ready)return <p role="status">Loading account…</p>;
 return <>{error&&<p role="alert" className="error">{error}</p>}<details id="account-access" className="account-access"><summary>{user?`Account · ${user.username}`:"Sign in / Join"}</summary><AccountPanel user={user} onChange={u=>{setUser(u);setError('');}}/>{user?.role==='moderator'&&<details className="moderator-workspace"><summary>Moderation workspace</summary><ReportQueue key={user.id}/><RemovalQueue/></details>}</details><ContributionWorkspace key={user?.id??'guest'} user={user}/></>;
}
function ContributionWorkspace({user}:{user:Account|null}){
 const [passages,setPassages]=useState<Passage[]>([]), [passageId,setPassageId]=useState('');
 const [records,setRecords]=useState<Saved[]>([]), [draft,setDraft]=useState<Draft>({...blank});
 const [editing,setEditing]=useState<Saved|null>(null), [busy,setBusy]=useState(false), [loading,setLoading]=useState(true);
 const [error,setError]=useState(''), [message,setMessage]=useState('');
 const [page,setPage]=useState(0);
 const [reference,setReference]=useState({edition:'',locator:'',url:''});
 const [opened,setOpened]=useState(false),[writing,setWriting]=useState(false),[step,setStep]=useState(0);
 useEffect(()=>{function search(target="catalog-search"){if(busy)return;if(writing&&JSON.stringify(draft)!==JSON.stringify(blank)&&!window.confirm('Discard this unsaved draft?'))return;setOpened(false);setWriting(false);setDraft({...blank});setEditing(null);requestAnimationFrame(()=>{const input=document.getElementById(target);input?.focus();input?.scrollIntoView({block:'center'});});}const refs=()=>search(),browse=()=>search('translated-search');window.addEventListener('ancientlens:search',refs);window.addEventListener('ancientlens:browse',browse);return()=>{window.removeEventListener('ancientlens:search',refs);window.removeEventListener('ancientlens:browse',browse);};},[busy,writing,draft]);
 function openContribution(id:string){window.location.hash='contribute-'+id;}
 useEffect(()=>{const route=()=>{const id=window.location.hash.replace('#contribute-','');if(!window.location.hash.startsWith('#contribute-')){setOpened(false);return;}if(!passages.some(p=>p.id===id))return;setPassageId(id);setPage(0);setOpened(true);setWriting(false);setStep(0);requestAnimationFrame(()=>document.getElementById('contribution-title')?.focus());};route();window.addEventListener('hashchange',route);return()=>window.removeEventListener('hashchange',route);},[passages]);
 function next(form:HTMLFormElement){const fields=form.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('[data-step="'+step+'"] input,[data-step="'+step+'"] textarea,[data-step="'+step+'"] select');for(const field of Array.from(fields)){if(!field.reportValidity())return;}setStep(n=>n+1);}
 const passage=passages.find(p=>p.id===passageId);
 const sourceObject=collection.find(r=>r.passages.some(p=>p.id===passageId));
 useEffect(()=>{let active=true;request<Passage[]>('/api/catalog/passages').then(data=>{if(active){setPassages(data);setPassageId(data[0]?.id??'');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true;setRecords([]);setReference({edition:"",locator:"",url:""});setDraft({...blank});setEditing(null);setMessage('');if(!passageId)return;
 setLoading(true);setError('');request<Saved[]>('/api/contributions?passage_id='+encodeURIComponent(passageId)+'&offset='+page*10).then(data=>{if(active)setRecords(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[passageId,page]);
 function update<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(d=>({...d,[key]:value,...(key==='terms_accepted'?{}:{terms_accepted:false})}));setMessage('');}
 async function withdraw(row:Saved){if(!window.confirm('Withdraw every revision of this contribution and request removal? Private history remains pending erasure review; previously licensed copies may persist.'))return;setBusy(true);setError('');try{await request('/api/contributions/'+encodeURIComponent(row.id)+'/withdraw',{method:'POST'});setEditing(null);setDraft({...blank});setMessage('Contribution withdrawn. Erasure review is pending; private history and backups remain.');setRecords(await request<Saved[]>('/api/contributions?passage_id='+encodeURIComponent(passageId)+'&offset='+page*10));}catch(e){setError(e instanceof Error?e.message:'Withdrawal failed');}finally{setBusy(false);}}
 async function save(event:FormEvent){event.preventDefault();if(step<2){next(event.currentTarget as HTMLFormElement);return;}const form=event.currentTarget as HTMLFormElement;for(const field of Array.from(form.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('input,textarea,select'))){if(!field.checkValidity()){setStep(Number(field.closest('[data-step]')?.getAttribute('data-step')??2));requestAnimationFrame(()=>field.reportValidity());return;}}setBusy(true);setError('');setMessage('');
 try{
  const payload=editing?{...draft,base_revision:editing.revision}:{...draft,passage_id:passageId};
  await request(editing?'/api/contributions/'+encodeURIComponent(editing.id)+'/revisions':'/api/contributions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});
  setDraft({...blank});setEditing(null);setWriting(false);setStep(0);setMessage('Draft saved · pending moderation · unreviewed.');
  try{setRecords(await request<Saved[]>('/api/contributions?passage_id='+encodeURIComponent(passageId)+'&offset='+page*10));}
  catch{setError('Your draft was saved, but the list could not refresh. Reload the page to see it.');}
 }catch(e){setError(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}}
 const latest=records.filter(row=>!records.some(other=>other.id===row.id&&other.revision>row.revision));
 function edit(row:Saved){const {author,translation_language,translation,source,reuse_terms,rights_basis,rights_evidence,notes,ai_assisted}=row;setDraft({author,translation_language,translation,source,reuse_terms:rights_basis==='original_work'?'CC BY-SA 4.0':reuse_terms,rights_basis,rights_evidence,notes,ai_assisted:Boolean(ai_assisted),terms_version:'2026-09-16.1',terms_accepted:false});setEditing(row);setWriting(true);setStep(0);setMessage('');}
 return <section className="contributions" aria-labelledby="contribution-title">
 <div className="explore-heading" style={{display:opened?'flex':'none'}}><div><p className="eyebrow">THE COLLECTION</p><h2 id="contribution-title" tabIndex={-1}>{opened?`${sourceObject?.title||passage?.monument||''} · ${passage?.designation||''}`:'Explore inscriptions'}</h2></div><span className="badge">Community · Pilot</span></div>
 <div hidden={opened}><CuratedCollection user={user} onContribute={openContribution}/><details id="reference-browser" className="reference-browser"><summary>Contribute a translation <span>Choose an inscription</span></summary><CatalogExplorer passages={passages} onOpen={p=>{setPassageId(p.id);setPage(0);setOpened(true);setWriting(false);setStep(0);requestAnimationFrame(()=>document.getElementById('contribution-title')?.focus());}}/></details></div>
 {opened&&<button disabled={busy} onClick={()=>{if(writing&&JSON.stringify(draft)!==JSON.stringify(blank)&&!window.confirm('Discard this unsaved draft?'))return;window.location.hash='explore';setOpened(false);setWriting(false);setDraft({...blank});setEditing(null);requestAnimationFrame(()=>document.getElementById('passage-'+passageId)?.focus());}}>← All passages</button>}
 {error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}
 {loading&&<p role="status">Loading catalog…</p>}
 {!loading&&!passages.length&&<p>No passages are available. Initialize and import the local catalog using the setup instructions.</p>}
 {opened&&!!passages.length&&<><label className="field">Choose passage<select value={passageId} disabled={busy||loading} onChange={e=>{if((editing||Object.values(draft).some((v,i)=>v!==Object.values(blank)[i]))&&!window.confirm('Discard the unsaved draft and change passage?'))return;setPage(0);setPassageId(e.target.value);}}>{passages.map(p=><option key={p.id} value={p.id}>{p.monument} · {collection.find(r=>r.passages.some(x=>x.id===p.id))?.accession||p.id} · {p.designation}</option>)}</select></label>
 {passage&&<details className="passage-evidence"><summary>Source & image status</summary><p><strong>{passage.locator}</strong></p><p>Source-reported reference · unreviewed. <a href={sourceLink(passage.source_url)} target="_blank" rel="noreferrer">{passage.source_title}</a></p><p>{passage.reviewed_image_links?'A reviewed image link is recorded in the catalog; image display is pending.':'No independently verified image alignment for this passage.'}</p></details>}
 <div className={sourceObject?"source-workspace":""}>{sourceObject&&<SourceContext item={sourceObject} passageId={passageId}/>}
 <div className={writing?"contribution-grid":"reading-layout"}><form hidden={!writing} noValidate onSubmit={save}><h3>{editing?`Revise draft · next revision ${editing.revision+1}`:'New translation draft'}</h3>{!user&&<p><button type="button" onClick={()=>window.dispatchEvent(new Event('ancientlens:account'))}>Sign in to contribute</button></p>}<ol className="steps" aria-label="Contribution progress">{["Translation","Sources","Credit & rights"].map((label,i)=><li key={label} aria-current={step===i?"step":undefined}><span>{i+1}</span>{label}</li>)}</ol><fieldset disabled={busy||loading||!user}><div data-step="0" hidden={step!==0}>

 <label className="field">Translation language<input required maxLength={200} placeholder="e.g. English" value={draft.translation_language} onChange={e=>update('translation_language',e.target.value)}/></label>
 <label className="field">Proposed translation<textarea required maxLength={20000} rows={6} value={draft.translation} onChange={e=>update('translation',e.target.value)}/></label>
 </div><div data-step="1" hidden={step!==1}><details><summary>Add a structured reference</summary><label className="field">Edition or author<input maxLength={500} value={reference.edition} onChange={e=>setReference({...reference,edition:e.target.value})}/></label><label className="field">Page or passage locator<input maxLength={200} value={reference.locator} onChange={e=>setReference({...reference,locator:e.target.value})}/></label><label className="field">Reference URL<input type="url" maxLength={1000} value={reference.url} onChange={e=>setReference({...reference,url:e.target.value})}/></label><button type="button" disabled={!reference.edition.trim()&&!reference.url.trim()} onClick={()=>{const addition=[reference.edition,reference.locator,reference.url].filter(Boolean).join(" · ");if((draft.source+"\n"+addition).length>4000){setError("Reference exceeds the source field limit.");return;}update("source",[draft.source,addition].filter(Boolean).join("\n"));setReference({edition:"",locator:"",url:""});}}>Add to evidence</button></details><label className="field">Sources and passage evidence<textarea required maxLength={4000} rows={3} placeholder="Edition / author:\nPage or passage:\nSource URL:\nEvidence and reasoning:" value={draft.source} onChange={e=>update('source',e.target.value)}/></label>
 </div><div data-step="2" hidden={step!==2}>
 <label className="field">Author credit<input required maxLength={200} value={draft.author} onChange={e=>update('author',e.target.value)}/></label>
 <label className="field">Basis for contributing<select value={draft.rights_basis} onChange={e=>{update('rights_basis',e.target.value as Draft['rights_basis']);update('reuse_terms',e.target.value==='original_work'?'CC BY-SA 4.0':'');}}><option value="original_work">My original work</option><option value="permission_supported">Work with permission or a reusable license</option></select></label>
 <label className="field">Reuse terms<input readOnly={draft.rights_basis==='original_work'} required maxLength={4000} placeholder="State the license or permission; it will need review" value={draft.reuse_terms} onChange={e=>update('reuse_terms',e.target.value)}/></label>
 <label className="field">Authorship or permission evidence<textarea required maxLength={4000} rows={2} placeholder="Declare your authorship or cite the permission and rights holder" value={draft.rights_evidence} onChange={e=>update('rights_evidence',e.target.value)}/></label>
 <label className="field">Uncertainty, alternatives and missing text<textarea maxLength={4000} rows={3} value={draft.notes} onChange={e=>update('notes',e.target.value)}/></label>
 <label><input type="checkbox" checked={draft.ai_assisted} onChange={e=>update('ai_assisted',e.target.checked)}/> AI assisted this contribution</label>
 <p><a href="/contributor-terms-2026-09-16.1.html" target="_blank" rel="noreferrer">Read contributor terms</a> · Original translations use CC BY-SA 4.0. Permission-supported text stays private pending separate rights clearance.</p>
 <label><input required type="checkbox" checked={draft.terms_accepted} onChange={e=>update('terms_accepted',e.target.checked)}/> I accept these terms for this revision and confirm my authorship or documented permission. For my original work, I grant CC BY-SA 4.0, including commercial reuse with attribution and share-alike.</label>
 </div><div className="wizard-actions">{step>0&&<button type="button" onClick={()=>setStep(n=>n-1)}>← Back</button>}{step<2?<button key="continue" className="primary" type="button" onClick={e=>next(e.currentTarget.form!)}>Continue →</button>:<button key="save" className="primary" type="submit">{busy?'Saving…':editing?'Save new revision':'Save unreviewed draft'}</button>} {editing&&<button type="button" onClick={()=>{setEditing(null);setDraft({...blank});}}>Cancel revision</button>}</div>
 </fieldset></form><div><button className="primary" hidden={writing} onClick={()=>{setWriting(true);setStep(0);}}>＋ Contribute a translation</button><h3>{user?.role==='moderator'?'Moderation workspace':'Translations'} · {latest.length}</h3><p>{user?.role==='moderator'?'All contributions for this passage appear here.':user?'Your drafts and allowed contributions appear here.':'Only contributions allowed through moderation appear here.'} All remain scholarly unreviewed.</p>
 {!latest.length&&!loading&&<p>No community translations yet. Published source text, where available, is shown separately above.</p>}
 {latest.map(row=><article className="draft-card" key={row.id}><h3>{row.author} · {row.translation_language}</h3><small>Revision {row.revision} · Unreviewed · {row.moderation_status.replace(/_/g,' ')}</small><p className="translation-text">{row.translation}</p><details><summary>Sources, credit & rights</summary><p><strong>Sources:</strong> {row.source}</p><p>{row.accepted_on?`Terms ${row.terms_version} accepted ${new Date(row.accepted_on).toLocaleString()}`:'Legacy revision: no recorded license acceptance'}</p><p><strong>Reuse declaration:</strong> {row.reuse_terms}</p><p><strong>Rights basis:</strong> {row.rights_basis==='original_work'?'Original work':'Permission-supported'}</p><p><strong>Evidence:</strong> {row.rights_evidence}</p><p>{row.ai_assisted?'AI-assisted contribution':'No AI assistance declared'}</p>{row.notes&&<p><strong>Uncertainty:</strong> {row.notes}</p>}</details><button hidden={!row.can_edit} disabled={busy||loading} onClick={()=>{if((editing||draft.translation)&&!window.confirm('Replace the unsaved form with this draft?'))return;edit(row);}}>Revise draft</button>
 {row.withdrawn?<p>Withdrawn · erasure review pending. Private history is retained.</p>:row.can_edit&&<button disabled={busy||loading} onClick={()=>void withdraw(row)}>Withdraw and request removal</button>}
 {row.can_moderate&&<ModerationPanel row={row} onSaved={async()=>setRecords(await request<Saved[]>('/api/contributions?passage_id='+encodeURIComponent(passageId)+'&offset='+page*10))}/>}
 {user&&<ReportForm key={row.revision} id={row.id} revision={row.revision}/>}
 <details><summary>Recent revision history ({records.filter(r=>r.id===row.id).length})</summary>{row.history_may_be_truncated&&<p>Older history is retained in the database but not all shown on this page.</p>}{records.filter(r=>r.id===row.id).map(old=><div key={old.revision}><h4>Revision {old.revision} · {old.author}</h4><p>{new Date(old.created_on).toLocaleString()} · {old.translation_language}</p><p className="translation-text">{old.translation}</p><p>Sources: {old.source}</p><p>Reuse: {old.reuse_terms}</p><p>{old.accepted_on?`Terms ${old.terms_version} accepted ${new Date(old.accepted_on).toLocaleString()}`:'No recorded license acceptance'}</p><p>Rights evidence: {old.rights_evidence}</p><p>Notes: {old.notes||'None'}</p><p>{old.ai_assisted?'AI-assisted':'No AI assistance declared'} · Unreviewed · {old.moderation_status.replace(/_/g,' ')}</p>{old.moderation_events.map(event=><p key={event.id}><strong>{event.action.replace(/_/g,' ')}:</strong> {event.reason} · {event.moderator} · {new Date(event.created_on).toLocaleString()}</p>)}</div>)}</details></article>)}
 <nav hidden={!latest.length&&page===0} aria-label="Contribution pages"><button disabled={page===0||busy||loading} onClick={()=>{if((editing||draft.translation)&&!window.confirm('Discard unsaved form changes?'))return;setPage(p=>p-1);}}>Previous page</button> <span>Page {page+1}</span> <button disabled={latest.length<10||busy||loading} onClick={()=>{if((editing||draft.translation)&&!window.confirm('Discard unsaved form changes?'))return;setPage(p=>p+1);}}>Next page</button></nav>
 </div></div></div></>}
 </section>;
}

function ModerationPanel({row,onSaved}:{row:Saved;onSaved:()=>Promise<void>}){
 const [action,setAction]=useState('changes_requested'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{
  await request('/api/contributions/'+encodeURIComponent(row.id)+'/moderation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:row.revision,base_event:row.moderation_events[row.moderation_events.length-1]?.id??0,action,reason})});
  setReason('');try{await onSaved();}catch{setError('Decision saved. Reload to refresh the list.');}
 }catch(e){setError(e instanceof Error?e.message:'Moderation failed');}finally{setBusy(false);}}
 return <form onSubmit={submit}><fieldset disabled={busy}><h4>Moderate this revision</h4><p>Allowing makes this revision visible to readers of this app. It remains scholarly unreviewed.</p><label className="field">Decision<select value={action} onChange={e=>setAction(e.target.value)}><option value="changes_requested">Request changes</option><option value="allowed">Allow visibility</option><option value="hidden">Hide contribution</option></select></label><label className="field">Moderation reason<textarea required maxLength={4000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert" className="error">{error}</p>}<button type="submit">{busy?'Saving…':'Record decision'}</button></fieldset></form>;
}
