import pilotSelection from './pilotSelection';
const editionIds=new Set(pilotSelection.selected.map(r=>r.id));
import {ArtifactPreview} from './ArtifactPreview';
import {sourceDates} from './sourceDates';
import {matches,topics,objectType,citation,recordText,downloadText} from './Discovery';
import {ReaderTools} from './ReaderTools';
import {ArtifactMap,atPlace,attributedRegions,discoveryPlaces} from './ArtifactMap';
import {PrivateRecord,libraryRequest,type SavedArtifact} from './Library';
import type {Account} from './Account';
import {useEffect,useState} from 'react';
import {collection} from './collection';
const activeId=()=>window.location.hash==='#artifact-shemai'?'cma-102365':window.location.hash.replace('#artifact-','').split('/')[0];
// Editorial card labels only; exact museum titles remain in the reading view and downloads.
const displayTitle=(title:string)=>title.split(';')[0].replace(/\s*\([^)]*\)/g,'').trim();
export function CuratedCollection({user,onContribute}:{user:Account|null;onContribute:(id:string)=>void}){
 const [id,setId]=useState(activeId),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[editionsOnly,setEditionsOnly]=useState(false);
 const [savedIds,setSavedIds]=useState<string[]>([]),[libraryError,setLibraryError]=useState('');
 useEffect(()=>{let active=true;const refresh=()=>{if(!user){setSavedIds([]);setSavedRows([]);return;}libraryRequest<SavedArtifact[]>('/api/library').then(rows=>{if(active){setSavedIds(rows.map(r=>r.artifact_id));setSavedRows(rows);setLibraryError('');}}).catch(e=>{if(active)setLibraryError(e.message);});};refresh();window.addEventListener('ancientlens:library-updated',refresh);return()=>{active=false;window.removeEventListener('ancientlens:library-updated',refresh);};},[user?.id]);
 useEffect(()=>{if(id==='#library'){setQuery('');setFilter('All');setTopic('');setKind('');setDateQuery('');setPeriod('');setPlace('');setEditionsOnly(false);}},[id]);
 const [place,setPlace]=useState('');
 const [topic,setTopic]=useState(''),[kind,setKind]=useState(''),[dateQuery,setDateQuery]=useState(''),[period,setPeriod]=useState(''),[compare,setCompare]=useState<string[]>([]),[notesOpen,setNotesOpen]=useState(false),[returnTo,setReturnTo]=useState('#explore');
 const [savedRows,setSavedRows]=useState<SavedArtifact[]>([]),[includeNotes,setIncludeNotes]=useState(false);
 const reset=()=>{setQuery('');setFilter('All');setTopic('');setKind('');setDateQuery('');setPeriod('');setPlace('');setEditionsOnly(false);};
 const [saving,setSaving]=useState<string[]>([]);
 async function saveArtifact(artifact:string){
  if(!user){window.dispatchEvent(new Event('ancientlens:account'));return;}
  if(savedIds.includes(artifact)){setNotesOpen(true);window.location.hash='artifact-'+artifact;return;}
  setSaving(ids=>[...ids,artifact]);setLibraryError('');
  try{const current=await libraryRequest<SavedArtifact>('/api/library/'+artifact);
   if(!current.saved)await libraryRequest('/api/library/'+artifact,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({notes:current.notes,version:current.version,remove:false})});
   setSavedIds(ids=>[...new Set([...ids,artifact])]);window.dispatchEvent(new Event('ancientlens:library-updated'));
  }catch(e){setLibraryError((e as Error).message);}finally{setSaving(ids=>ids.filter(id=>id!==artifact));}
 }
 const featured=collection[0];
 const map=id==='#map';
 const library=id==='#library';
 const item=collection.find(r=>r.id===id);
 useEffect(()=>{const sync=()=>setId(activeId());window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[]);
 useEffect(()=>{if(item){document.getElementById('artifact-title')?.focus();const anchor=window.location.hash.split('/')[1];if(anchor)requestAnimationFrame(()=>document.getElementById(anchor)?.scrollIntoView({block:'start'}));if(notesOpen)requestAnimationFrame(()=>document.querySelector<HTMLTextAreaElement>('#private-note-editor textarea')?.focus());}else{setNotesOpen(false);setReturnTo(map?'#map':library?'#library':'#explore');}},[item,map,library]);
 if(!item){const visible=collection.filter(r=>(!library||savedIds.includes(r.id))&&(!editionsOnly||editionIds.has(r.id))&&(!map||atPlace(r.id,place))&&(filter==='All'||r.collection===filter)&&matches(r,query,library&&user?savedRows.find(n=>n.artifact_id===r.id)?.notes:'')&&(!topic||topics(r).includes(topic))&&(!kind||objectType(r)===kind)&&r.date.toLowerCase().includes(dateQuery.toLowerCase())&&(!period||(!!sourceDates[r.id]&&sourceDates[r.id][0]<=Number(period.split(',')[1])&&sourceDates[r.id][1]>=Number(period.split(',')[0]))));return <section className="translated-collection" aria-labelledby="collection-title">
 {!library&&!map&&<section className="discovery-hero" aria-labelledby="discovery-title"><div className="hero-copy"><p className="eyebrow">THE OPEN INSCRIPTION COLLECTION</p><h1 id="discovery-title">Discover what<br/>ancient objects <em>say.</em></h1><p className="hero-description">Explore sourced translations. Save your discoveries.</p><form className="hero-search" role="search" onSubmit={e=>{e.preventDefault();document.getElementById('translated-search')?.focus();document.getElementById('collection-title')?.scrollIntoView({block:'start'});}}><label htmlFor="hero-query">Explore the collection</label><div><input id="hero-query" type="search" placeholder="Search names, objects, inscriptions…" value={query} onChange={e=>setQuery(e.target.value)}/><button type="submit" aria-label="Show matching artifacts">↗</button></div></form><p className="hero-stats">{collection.length} artifacts <span>·</span> {new Set(collection.map(r=>r.collection)).size} collections <span>·</span> Free</p></div><a className="hero-object" href={'#artifact-'+featured.id}><img src={featured.image} alt={featured.title} fetchPriority="high"/><div><span>IN FOCUS · EGYPT</span><strong>{featured.title} <span aria-hidden="true">↗</span></strong><small>{featured.date} · Cleveland Museum of Art · CC0</small></div></a></section>}
 <div className="collection-heading"><h2 id="collection-title">{library?'My Library':map?'Explore by place':'Find your next discovery'}</h2><span>{library?`${savedIds.length} saved artifacts`:`${collection.length} artifacts · English source readings`}</span></div>
 {library&&<><p>Your saved artifacts. Private to your account.</p>{!user&&<button onClick={()=>window.dispatchEvent(new Event('ancientlens:account'))}>Sign in to view your library</button>}{libraryError&&<p role="alert">{libraryError}</p>}{user&&<button onClick={async()=>{try{const rows=await libraryRequest<unknown[]>('/api/library');const url=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ancientlens-my-library.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setLibraryError((e as Error).message);}}}>Export my records</button>}</>}
 {!library&&<div className="filter-row"><a href="#explore" aria-current={!map?'page':undefined}>Grid</a><a href="#map" aria-current={map?'page':undefined}>Map</a></div>}
 <div className="collection-search"><label htmlFor="translated-search">{library?'Search saved artifacts and notes':'Find an artifact'}</label><input id="translated-search" type="search" placeholder={library?"Search your artifacts and private notes…":"Search artifacts, names or inscriptions…"} value={query} onChange={e=>setQuery(e.target.value)}/></div>
 <div className="filter-row culture-filters" aria-label="Artifact collection">{['All',...new Set(collection.map(r=>r.collection))].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f!=='All'&&<img src={collection.find(r=>r.collection===f)!.image} alt="" loading="lazy"/>}{f}</button>)}</div>
 <label className="edition-filter"><input type="checkbox" checked={editionsOnly} onChange={e=>setEditionsOnly(e.target.checked)}/> Illustrated editions ({editionIds.size})</label><small>Published inscription coverage checked against the source. Includes damaged texts; scholarly review remains unreviewed.</small>
 <div className="discovery-refine"><label>Topic<select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">All topics</option>{[...new Set(collection.flatMap(topics))].map(t=><option key={t}>{t}</option>)}</select></label><label>Object type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="">All types</option>{[...new Set(collection.map(objectType))].map(t=><option key={t}>{t}</option>)}</select></label><label>Period<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="">Any period</option><option value="-10000,-1001">Before 1000 BCE</option><option value="-1000,-1">1000–1 BCE</option><option value="1,600">1–600 CE</option><option value="601,1500">601–1500 CE</option></select></label><label>Date wording<input value={dateQuery} onChange={e=>setDateQuery(e.target.value)} placeholder="e.g. 400 or BCE"/></label></div><small>Topics and types are editorial discovery aids. Period filters include overlapping museum date ranges; dates remain approximate. Date wording searches the displayed label.</small>
 {(query||filter!=='All'||topic||kind||dateQuery||period||place||editionsOnly)&&<p className="active-filters">Active: {[editionsOnly?'Illustrated editions':'',query,filter!=='All'?filter:'',topic,kind,dateQuery,period?({'-10000,-1001':'Before 1000 BCE','-1000,-1':'1000–1 BCE','1,600':'1–600 CE','601,1500':'601–1500 CE'}[period]):'',map?(attributedRegions.find(p=>p.id===place)?.name??discoveryPlaces.find(p=>p.id===place)?.name??place):''].filter(Boolean).join(' · ')} <button onClick={reset}>Clear all filters</button></p>}
 {library&&user&&<div className="library-export"><label><input type="checkbox" checked={includeNotes} onChange={e=>setIncludeNotes(e.target.checked)}/> Include my private notes in reading-sheet export</label><button onClick={()=>downloadText('ancientlens-reading-sheets.txt',collection.filter(r=>savedIds.includes(r.id)).map(r=>recordText(r)+(includeNotes?'\n\nPRIVATE PERSONAL NOTE (not source text):\n'+(savedRows.find(n=>n.artifact_id===r.id)?.notes||''):'' )).join('\n\n==========\n\n'))}>Export reading sheets</button></div>}
 {compare.length>0&&<section className="comparison"><h3>Compare objects ({compare.length}/3)</h3><button onClick={()=>setCompare([])}>Clear comparison</button><div className="comparison-grid">{collection.filter(r=>compare.includes(r.id)).map(r=><article key={r.id}><a href={'#artifact-'+r.id}>{r.title}</a><p>{r.accession} · {r.date}</p><ArtifactPreview item={r}/><blockquote>{r.passages[0].text}</blockquote><small>First source entry · unreviewed. Image alignment unverified. {r.note} Open record for all passages.</small><button aria-label={`Remove ${r.title} (${r.accession}) from comparison`} onClick={()=>setCompare(ids=>ids.filter(id=>id!==r.id))}>Remove from comparison</button></article>)}</div></section>}
 <p className="collection-caption">Published readings · Includes partial excerpts, names and coin legends · Scholarly review: unreviewed</p>{!library&&libraryError&&<p role="alert">{libraryError}</p>}
 <div className={map?"map-discovery-layout":"collection-results"}>{map&&<ArtifactMap selected={place} onSelect={setPlace}/>}<div><p role="status" className="collection-count">{library?`${visible.length} of ${savedIds.length} saved artifacts`: `${visible.length} artifact${visible.length===1?'':'s'}`}</p>
 <div className="artifact-grid">{visible.map(r=><article className="artifact-card" key={r.id}><div className="artifact-media"><a href={'#artifact-'+r.id} className="artifact-photo"><ArtifactPreview item={r}/><span>{r.collection}</span></a><button className="card-save" aria-label={savedIds.includes(r.id)?'Open saved record: '+displayTitle(r.title):'Save '+displayTitle(r.title)} disabled={saving.includes(r.id)} onClick={()=>void saveArtifact(r.id)} title={savedIds.includes(r.id)?'Open saved record':'Save to My Library'}><svg viewBox="0 0 24 24" aria-hidden="true" fill={savedIds.includes(r.id)?'currentColor':'none'}><path d="M6 3h12v18l-6-4-6 4Z"/></svg></button></div><div className="artifact-card-body"><small>{r.date}{r.id.startsWith("cma-")?" · "+r.accession:""}</small><h3><a href={'#artifact-'+r.id}>{displayTitle(r.title)}</a></h3>{library&&savedRows.find(n=>n.artifact_id===r.id)?.notes&&<p className="note-excerpt">Private note: {savedRows.find(n=>n.artifact_id===r.id)!.notes.slice(0,140)}</p>}<label className="compare-toggle"><input type="checkbox" aria-label={`Compare ${r.title} (${r.accession})`} checked={compare.includes(r.id)} disabled={!compare.includes(r.id)&&compare.length>=3} onChange={e=>setCompare(ids=>e.target.checked?[...ids,r.id]:ids.filter(id=>id!==r.id))}/> Compare</label><a className="artifact-read" href={'#artifact-'+r.id}>Read {['maya-copan-stela-64','maya-ccit-vaso-8','maya-ccit-pntf-192'].includes(r.id)?'published edition':r.id.startsWith('maya-')?'excerpt':r.id==='cma-138393'?'sculptor names':r.passages.length===1?'translation':r.passages.length+' inscriptions'} <span aria-hidden="true">↗</span></a></div></article>)}</div>
 {!visible.length&&<p>{library&&!savedIds.length?'Save an artifact to start your library.':'No matching artifacts. Clear filters, or try a topic such as burial, coins or mirrors.'}</p>}</div></div><p className="collection-caption">Sources: Cleveland, Walters and ClassicMayan. Text and image licences may differ; see each record for credit, reuse terms and coverage.</p></section>;}
 return <section className="curated-collection" aria-labelledby="artifact-title"><a className="back-link" href={returnTo}>← {returnTo==='#library'?'My Library':returnTo==='#map'?'Map results':'All artifacts'}</a>
 <article className="curated-artifact"><figure>{item.image?<a href={item.image} target="_blank" rel="noreferrer"><ArtifactPreview item={item}/></a>:<ArtifactPreview item={item}/>}<figcaption>{item.institution} · {item.accession} · {item.image?item.image_license+" image":"Text-only record"}. <a href={item.source_url} target="_blank" rel="noreferrer">View published source ↗</a></figcaption></figure>
 <div><p className="eyebrow">{item.collection} COLLECTION{item.source_language!=='Not independently classified'&&<> · {item.source_language} TEXT</>}</p><h2 id="artifact-title" tabIndex={-1}>{item.title}</h2><p>{item.date}</p><span className="badge">AncientLens review: unreviewed</span><p className="source-line">{['maya-copan-stela-64','maya-ccit-vaso-8','maya-ccit-pntf-192'].includes(item.id)?'Published edition · Fragmentary':item.id.startsWith('maya-')?'Published excerpt · English':item.id==='cma-138393'?'Museum reading · Two sculptor names':'Museum translation · English'} · Original wording</p><p className="source-caveat">Source spelling, typos and gaps are preserved. {item.image?"Image alignment is unverified.":"Text-only record; image alignment is unavailable."}</p><ReaderTools key={item.id} item={item}/>{item.description&&<p className="object-intro"><strong>From the museum description: </strong>{item.description.split(/(?<=[.!?])\s/)[0]} <button onClick={()=>{const d=document.getElementById("museum-description") as HTMLDetailsElement;d.open=true;d.scrollIntoView({block:"center"});}}>Read full description</button></p>}
 {editionIds.has(item.id)&&<details><summary>Why this record is in Illustrated editions</summary><p>{pilotSelection.selected.find(r=>r.id===item.id)?.coverage}</p><p>{pilotSelection.selected.find(r=>r.id===item.id)?.coverage_evidence}</p><p>{pilotSelection.selected.find(r=>r.id===item.id)?.visual_observation}</p><p>Editorial source-coverage check; AncientLens scholarly review remains unreviewed.</p></details>}
 {item.note&&<p className="notice">{item.note}</p>}
 <details className="reader-library" open={notesOpen} onToggle={e=>setNotesOpen(e.currentTarget.open)}><summary>Save &amp; private notes</summary><PrivateRecord key={item.id+"-"+(user?.id??"guest")} artifact={item.id} user={user}/></details>
 <details><summary>Reading notes</summary><p>Published translations may cover only part of the object or a short name. Original typos, uncertainty and gaps are preserved. The object image may not show every inscribed side; exact image alignment is unverified.</p></details>
 {item.passages.map((p,i)=><section className="curated-passage" key={p.id}><h3 id={"inscription-"+(i+1)}>Inscription {i+1}</h3><details className="passage-citation"><summary>Cite this passage</summary><p>{citation(item,p)}</p></details><blockquote lang="en">{p.text.length>1200?p.text.split(/(?<=\.) (?=[A-Z])/).map((text,j)=><span className="reading-paragraph" key={j}>{text}{j<p.text.split(/(?<=\.) (?=[A-Z])/).length-1?" ":""}</span>):p.text}</blockquote><button onClick={()=>onContribute(p.id)}>Contribute / community translations ↗</button>{p.remark&&<details><summary>Source passage note</summary><p>{p.remark}</p></details>}{p.source_text&&<details><summary>Source transcription</summary><p lang={item.source_language==='Greek'?'grc':item.source_language==='Chinese'?'zh':item.source_language==='Latin'?'la':'und'}>{p.source_text}</p></details>}</section>)}
 {item.description&&<details id="museum-description"><summary>Museum description and alternative wording</summary><p>{item.description}</p></details>}
 <details><summary>Source, rights and provenance</summary><p><a href={item.source_url} target="_blank" rel="noreferrer">Published source ↗</a> · <a href={item.metadata_url} target="_blank" rel="noreferrer">Source page ↗</a></p><p>Snapshot: {item.retrieved_at.slice(0,10)}. Text: <a href={item.text_rights_url}>{item.text_license}</a>. {item.image?<>Image: <a href={item.image_rights_url}>{item.image_license}</a>.</>:<>No image included.</>} {item.id.startsWith("maya-")?item.institution:"Individual translator not identified in the imported fields."} {item.text_changes} {item.image_changes}</p><p>{item.culture.join('; ')}</p><p>No independent AncientLens scholarly review. Language and collection labels are editorial classifications.</p><a href={item.record_url} download>Download record</a> · <a href={item.source_snapshot} download>Source evidence</a></details>
 {collection.some(r=>r.id!==item.id&&r.collection===item.collection)&&<section className="related-objects"><h3>Explore related objects</h3><p>Same editorial collection · not a historical relationship claim</p>{collection.filter(r=>r.id!==item.id&&r.collection===item.collection).sort((a,b)=>Number(objectType(b)===objectType(item))-Number(objectType(a)===objectType(item))).slice(0,3).map(r=><a key={r.id} href={'#artifact-'+r.id}>{r.title} · {r.accession}</a>)}</section>}<div className="print-provenance"><h3>Source and reuse</h3><p>{citation(item)}</p><p>{item.note} Image may not show all translated surfaces. Private notes are excluded.</p></div>
 </div></article></section>;
}
