import {useEffect,useState,type FormEvent} from 'react';
async function call(url:string,body?:unknown){const response=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'Check the report fields.');return data;}
export function ReportForm({id,revision}:{id:string;revision:number}){
 const [reason,setReason]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setStatus('');try{await call('/api/contributions/'+encodeURIComponent(id)+'/reports',{revision,reason});setReason('');setStatus('Report received. Only moderators can read it. Reporting does not automatically hide a contribution.');}catch(e){setStatus(e instanceof Error?e.message:'Report failed');}finally{setBusy(false);}}
 return <details><summary>Report this revision</summary><p>Describe a rights, attribution, abuse or content concern. Do not include passwords or recovery codes.</p><form onSubmit={submit}><label className="field">Report reason<textarea required maxLength={4000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy}>{busy?'Sending…':'Send private report'}</button>{status&&<p role="status">{status}</p>}</form></details>;
}
type Report={id:number;contribution_id:string;revision:number;reason:string;created_on:string;passage_id:string;designation:string;reporter:string;translation:string;author:string};
export function ReportQueue(){
 const [rows,setRows]=useState<Report[]>([]),[error,setError]=useState(''),[after,setAfter]=useState(0),[loading,setLoading]=useState(false);
 async function refresh(){setRows(await call('/api/reports?after='+after));}
 useEffect(()=>{let active=true;setRows([]);setLoading(true);setError('');call('/api/reports?after='+after).then(data=>{if(active)setRows(data);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[after]);
 return <section className="account-panel"><h2>Private report queue</h2><p>Resolving a report records your response. Use the passage moderation controls separately if visibility should change.</p>{loading&&<p role="status">Loading reports…</p>}{error&&<p role="alert">{error}</p>}{!loading&&!rows.length&&<p>No open reports on this page.</p>}{rows.map(row=><ReportItem key={row.id} row={row} refresh={refresh}/>)}<button disabled={!after||loading} onClick={()=>setAfter(0)}>First reports</button> <button disabled={rows.length<20||loading} onClick={()=>setAfter(rows[rows.length-1].id)}>Next reports</button></section>;
}
function ReportItem({row,refresh}:{row:Report;refresh:()=>Promise<void>}){
 const [reason,setReason]=useState(''),[outcome,setOutcome]=useState('action_taken'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function resolve(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{await call('/api/reports/'+row.id+'/resolve',{outcome,reason});try{await refresh();}catch{setError('Resolution saved. Reload to refresh the queue.');}}catch(e){setError(e instanceof Error?e.message:'Resolution failed');}finally{setBusy(false);}}
 return <article className="draft-card"><h3>{row.designation} · revision {row.revision}</h3><p>Reported by {row.reporter}: {row.reason}</p><details><summary>Reported text by {row.author}</summary><p className="translation-text">{row.translation}</p></details><form onSubmit={resolve}><label className="field">Resolution<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="action_taken">Action taken</option><option value="dismissed">Dismissed</option></select></label><label className="field">Resolution reason<textarea required maxLength={4000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button disabled={busy}>Resolve report</button></form></article>;
}
