"""Build the founder-approved bounded CC0 collection from pinned local evidence."""
import hashlib
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SELECTION=json.loads((ROOT/'scripts/collection_selection.json').read_text())
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def build():
 out=ROOT/'frontend/public/curated';acq=json.loads((out/'sources/acquisition.json').read_text());records=[];accessions=set()
 for selected in SELECTION:
  ident=selected['id']
  source=out/'sources'/f'cma-{ident}.json';d=json.loads(source.read_text());image=out/f'cma-{ident}.jpg'
  if d['id']!=ident or d['share_license_status']!='CC0':raise ValueError('Identity or rights mismatch')
  accession=d['accession_number']
  if accession in accessions or accession.endswith(('.a','.b')) or 'Replica' in d['title']:raise ValueError('Duplicate/side-only/replica entry')
  accessions.add(accession)
  passages=[dict(id=f'cma-{ident}-{n}',field=f'inscriptions[{n}].inscription_translation',text=i['inscription_translation'],source_text=i.get('inscription') or '',remark=i.get('inscription_remark') or '') for n,i in enumerate(d['inscriptions']) if (i.get('inscription_translation') or '').strip()]
  if not passages or not image.read_bytes().startswith(b'\xff\xd8'):raise ValueError('Missing translation or JPEG')
  record=dict(id=f'cma-{ident}',title=d['title'],accession=accession,date=d['creation_date'],culture=d.get('culture',[]),
   collection=selected['collection'],
   source_language=selected['source_language'],language='English',review='unreviewed',
   institution='The Cleveland Museum of Art',source_url=f'https://www.clevelandart.org/art/{accession}',metadata_url=f'https://openaccess-api.clevelandart.org/api/artworks/{ident}',
   retrieved_at=selected['retrieved_at'],metadata_sha256=sha(source),text_license='CC0',image_license='CC0',text_rights_url=acq['text_rights_url'],image_rights_url=acq['image_rights_url'],
   image=f'/curated/cma-{ident}.jpg',image_url=d['images']['web']['url'],image_sha256=sha(image),image_changes='None; museum web-sized JPEG',
   text_changes='None; translated fields and remarks reproduced verbatim',passages=passages,
   source_snapshot=f'/curated/sources/cma-{ident}.json',record_url=f'/curated/cma-{ident}.json',
   note=selected['note'],
   description=d['description'] if ident in (102365,138393) else '')
  (out/f'cma-{ident}.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n');records.append(record)
 for record in json.loads((ROOT/'scripts/maya_selection.json').read_text()):
  evidence=out/('sources/'+record['id']+'.json')
  d=json.loads(evidence.read_text())
  assert record['metadata_sha256']==sha(evidence) and record['text_license']=='CC BY 4.0'
  assert record['passages'][0]['text']==d['text'] and d['text'] in d['source_context']
  assert record['review']=='unreviewed' and not record['image']
  (out/(record['id']+'.json')).write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n')
  records.append(record)
 (out/'collection.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n')
 (ROOT/'frontend/src/collection.ts').write_text('// Generated by scripts/build_collection.py from pinned museum evidence.\nexport const collection = '+json.dumps(records,ensure_ascii=False,indent=2)+';\n')
 (ROOT/'backend/app/data/catalog/curated.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n')
 print(f'{len(records)} distinct artifacts, {sum(len(r["passages"]) for r in records)} translated entries; no community catalog writes')
if __name__=='__main__':build()
